config/routes.rb
BasicRailsCRUD::Application.routes.draw do
  resources :persons  #does the exact same as all below
  # if using a GET it will usually return a HTML, nulipotent, doens't change!
  # if POST PUT PATCH DELETE, it will usually redirect to a get; itempotent makes changes! 

  ##### FOR JSON API
  # resources :persons, except: [:new, :edit]


 root 'persons#index'
 #  get 'persons' => 'persons#index'  # list all person # gets are nulipotent, doesn't change anything, safe, only gets
 #  get 'persons/new' => 'persons#new' #form to add a new person
 # # new needs to be before :id, it thinks new is the id!
 #  get 'persons/:id' =>  'persons#show' #name of collection passing in an id  #show one person

  
 #  get 'persons/:id/edit' => 'persons#edit' #form to edit person

 #  post 'persons' => 'persons#create' #create a new person, ust like p = Person.new?
 #  put 'persons/:id' => 'persons#update' #update a person
 #  patch 'persons/:id' => 'persons#update' #update an attribute of a person
 #  delete 'persons/:id' => 'persons#destroy' #delete a person, delete from a db, objects get destroyed
end


# the prefix in rake routes are the url paths! root_url, persons_url

app/models/person.rb
class Person
	include Mongoid::Document  # provides persistence
	# attr_accessor :name, :age, :eye_color  #creates getters and setters on a ruby class

	attr_accessor :is_angry  #this is not related to the mongoid persistance layer, it won't be saved in db

	field :name, type: String  # these are the persistence fields in mongoid
	field :age, type: Integer  # field also creates getters and setters?
	field :is_a_clown, type: Boolean, default: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController # notice it's plural because we're working with a collection
	
	# List all persons (show tabel of person in HTML)
	def index
		@persons = Person.all.entries #weird quirk of mongoid that returns a curser, not an array of all
		#@ instance variable
		#@@ class variables

		#render json: @persons #skips the view, and just renders out the json

	end

	# Show detail for a person with ID = params[:id] (in HTML)
	def show
		@person = Person.find_by(id: params[:id])
		# render json: @person #skips the view, and just renders out the json
	end

	# Form for adding a new person (in HTML)
	def new
		@person = Person.new
		# render json: @person #skips the view, and just renders out the json
	end

	# POST to this to crea a new person, then redirect to show
	def create
		@person = Person.create(person_params)
		redirect_to person_url(@person)
	end

	#Form for updating a person with ID = params[:id] (in HTML)
	def edit
		@person = Person.find_by(id: params[:id])
		# @person.save
		# render json: @person #skips the view, and just renders out the json
	end

	# PUT or PATCH to this to update person with ID = params[:id] , then redirect to show
	def update
		@person = Person.find_by(id: params[:id])
		@person.update_attributes(person_params)

		# Same as below!
		# @person.name = params[:person][:name]
		# @person.age = params[:person][:age]
		# @person.is_a_clown = params[:person][:is_a_clown]
		# @person.save

		# redirect_to 'index'
		redirect_to person_url(@person)  # the prefix from rake routes, could also use path..
	end
	
	# Destroy the person with ID = params[:id]
	# then redirect to index to list remaining persons
	def destroy
		@person = Person.find_by(id: params[:id])
		@person.destroy
		redirect_to persons_url
	end
	
	def person_params
		params.require(:person).permit(
			:name, :age, :is_a_clown
			)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_form.html.slim
= form_for @person do |f|
  p
    = f.label :name
    br
    = f.text_field :name
  p
    = f.label :age
    br
    = f.text_field :age
  p
    = f.label :is_a_clown
    br
    = f.check_box :is_a_clown
  p
    = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicRailsCRUD</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/persons/edit.html.slim
h1 Edit #{@person.name}

== render partial: 'layouts/form'

app/views/persons/index.html.slim
h1 
	span This is the list page 
	= link_to "New", new_person_url

/ ul
/ 	- @persons.each do |person|
/ 		li #{person.name} (#{person.id}) #{link_to "X", person_url(person), method: :delete, confirm: "Are you sure?"}
	

/ br
/ br

/ table 
/ 	- @persons.each do |person|
/ 		tr
/ 			td #{person.name}
/ 			td #{person.id}
/ 			td = link_to person.name, person_url(person)

/ br
/ br

table
  - @persons.each do |p|
    tr
      td style="width: 60%" #{p.name}
      td = link_to "Show", person_url(p)
      td = link_to "Edit", edit_person_url(p)
      td = link_to "Delete", person_url(p), method: :delete, confirm: "Are you sure?"

app/views/persons/new.html.slim
h1 Add a new person

== render partial: 'layouts/form'

app/views/persons/show.html.slim
h1 = @person.name 

p = @person.age
p ID #{@person.id}

p above is an example of slim's eval and print (=) and ruby string interpolation